### ISSUE TITLE
Adquirir Dados

### ISSUE THREAD

**Issue by ebl4** [JoaoGFarias/BDGeografico-Projeto2#1]
- Encontrar e validar shape
- Configurar o projeto com os dados
- Pesquisar e validar shape “reserva"

**Comment by JoaoGFarias** [comment]
Keep watching this issue -> @leoribeiro36 @gcpa

**Comment by ebl4** [comment]
Consegui dados no script

**Comment by JoaoGFarias** [comment]
@ebl4, adiciona alguma documentação de como preparar o ambiente.
É straightforward? Se for, podes fechar a issue.

**Comment by ebl4** [comment]
Ainda não consegui configurar o ambiente. Fiz estes exemplos no CIn. Porém to seguindo estes passos

1 - Instalar o postgreSQL disponível aqui em
http://www.enterprisedb.com/products-services-training/pgdownload#windows

2 - Vai na guia postgreeSQL 9.5 e executa **Aplication Stack Builder**

3 - Seleciona no item **Spartial** Database o PostGis para então baixar e instalar

4 - Baixar os scripts que estão na **conta do github** (já extraí do shape o sql que importa para criar o esquema e povoamento do banco de dados)

5 - Executar os scripts no **pgAdmin III** para criar o esquema do banco e povoamento. Seleciona um banco de dados (postgree por exemplo) clica no ícone SQL e executa os comandos.

6 - Baixar e instalar o OpenJump para **visualizar os dados geográficos**.

7 - Realizar as consultas no pgAdmin III. Acho que para algumas consultas o mapa retornado deve ser visualizado no OpenJump.

**Comment by JoaoGFarias** [comment]
@ebl4, estou com problemas no passo 5. Podias destilar melhor?

Estou conectado no servidor default que o pgAdmin III cria, mas não entendi como faço para executar os scripts SQL.

<img width="1264" alt="screen shot 2015-11-29 at 6 03 06 pm" src="https://cloud.githubusercontent.com/assets/1585655/11460043/aae5700e-96c3-11e5-9997-dd9af27f9a3a.png">

<img width="767" alt="screen shot 2015-11-29 at 6 03 16 pm" src="https://cloud.githubusercontent.com/assets/1585655/11460046/b0187ad0-96c3-11e5-87f0-db4eab094c29.png">

Qual é o procedimento agora?

**Comment by JoaoGFarias** [comment]
@ebl4, só para confirmar, a imagem abaixo é o resultado esperado da query (ainda) mais abaixo?

<img width="989" alt="screen shot 2015-11-29 at 6 30 54 pm" src="https://cloud.githubusercontent.com/assets/1585655/11460212/922b4c60-96c7-11e5-951f-bbe4f0b6322e.png">

``` sql
select * from afg_airports_airfields, afg_districts_329
where ST_Distance (afg_airports_airfields.geom, afg_districts_329.geom) < 100
```

**Comment by JoaoGFarias** [comment]
Fechando essa issue; problemas de configuração estão sendo atacados em #6
