### ISSUE TITLE
Implementar consultas de relacionamento espacial

### ISSUE THREAD

**Issue by ebl4** [JoaoGFarias/BDGeografico-Projeto2#2]
- Distance ( geometry, geometry ) - Review
- Equals ( geometry, geometry ) - Review
- Disjoint ( geometry, geometry ) - Review
- Intersects ( geometry, geometry ) - Review
- Touches ( geometry, geometry ) - Review
- Crosses ( geometry, geometry ) - Review
- Within ( geometry, geometry ) - Review
- Overlaps ( geometry, geometry ) - Review
- Contains ( geometry, geometry ) - Review

**Comment by JoaoGFarias** [comment]
Second assignee -> @leoribeiro36

**Comment by JoaoGFarias** [comment]
@ebl4 e @leoribeiro36, vão marcando as consultas que estão ok.
Vou fazer o mesmo na #3 

@ebl4, tinha algum lixo do merge que removi (fe5164a ); apesar dos arquivos não serem executáveis, tenta evitar deixar isso para não acumular :)

**Comment by ebl4** [comment]
Atualizei as consultas de relacionamento espacial em uma pasta separada para evitar conflitos. Pasta "queries"
