### ISSUE TITLE
Implementar consultas de processamento geométrico

### ISSUE THREAD

**Issue by ebl4** [JoaoGFarias/BDGeografico-Projeto2#3]
- Centroid (geometry) - Review
- Area (geometry) - Review
-  Length (geometry) - Review
-  PointOnSurface (geometry) - WIP - Ver [comentário](https://github.com/JoaoGFarias/BDGeografico-Projeto2/issues/3#issuecomment-160808659)
-  Boundary (geometry) - Review
-  Buffer (geometry, double, [integer]) - Review
-  Intersection (geometry, geometry) - Review
-  Difference (geometry, geometry) - Review
-  ST_Union (geometry, geometry) - Review

**Comment by JoaoGFarias** [comment]
Second assignee -> @gcpa

**Comment by JoaoGFarias** [comment]
@gcpa, já começasse a atacar essa issue?
Me synca para planejarmos como terminá-la.
Se achares melhor, podes quebrá-la

**Comment by JoaoGFarias** [comment]
[Referência do PostGis](http://postgis.net/docs/reference.html#Geometry_Processing)

**Comment by JoaoGFarias** [comment]
[Inseri a lista de consultas a serem realizadas](https://github.com/JoaoGFarias/BDGeografico-Projeto2/commit/c09671076fac5e91545ed9934830af191b2ad619)

@gcpa, dá uma revisada. O nome das cidades, estradas e airfields não importa; pode mudar a vontade para termos um resultado visível.

Também estou marcando como Review as queries que fiz e precisam de revisão.

**Comment by JoaoGFarias** [comment]
[Consegui](https://github.com/JoaoGFarias/BDGeografico-Projeto2/commit/64e157fc80a8c1ff76eed48050af8861114c6460) fazer o ST_PointOnSurface pegar um ponto; o modo com que ele é calculado é determinístico, rodar ele de novo não me dá outro ponto.
Precisamos pensar como usá-lo para pegar 5 pontos diferentes.
