### ISSUE TITLE
Investigar como adicionar dados no arquivo de shape

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/BDGeografico-Projeto2#5]
Provavelmente deve se fazer necessário adicionar dados fictícios para realizar as consultas

**Comment by ebl4** [comment]
Realizei backup dos dados, pois não consegui gerar script.

Outra dúvida foi gerar shape a partir de uma consulta sql

Por exemplo, retornar uma área em uma consulta e após gerar o shape desta consulta.
