### ISSUE TITLE
Configurar o ambiente - Tutorial

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/BDGeografico-Projeto2#6]
Essa issue tem como objetivo determinar como configurar o ambiente para realizarmos as consultas.

1 - Instalar o postgreSQL disponível aqui em
http://www.enterprisedb.com/products-services-training/pgdownload

2 - Executar o Aplication Stack Builder

3 - Adicionar a extensão do PostGis

_No pgAdminIII_

4 - Executar o seguinte comando no banco de dados criado por _default_

``` sql
CREATE EXTENSION postgis;
```

5 - Executar os 4 scripts da pasta _scripts_

6 - No OpenJump, conectar no mesmo banco e realizar as consultas.

Resultado esperado da consulta

``` sql
select * from afg_airports_airfields, afg_districts_329
where ST_Distance (afg_airports_airfields.geom, afg_districts_329.geom) < 100
```

<img width="989" alt="screen shot 2015-11-29 at 6 30 54 pm" src="https://cloud.githubusercontent.com/assets/1585655/11460212/922b4c60-96c7-11e5-951f-bbe4f0b6322e.png">

**Comment by JoaoGFarias** [comment]
@ebl4, @gcpa e @leoribeiro36 
Vocês tiveram o mesmo resultado?

**Comment by ebl4** [comment]
Massa, João! Tu é o cara. Parei exatamente neste ponto

CREATE EXTENSION postgis;

**Comment by ebl4** [comment]
Vou atualizar as lista e as consultas que realizei. Ta faltando testar.

**Comment by ebl4** [comment]
Nova tabela inserida no backup. Não encontrei como gerar o script de uma tabela ou banco com dados já povoado.

**Comment by ebl4** [comment]
Link dos dados shapefiles 
https://esoc.princeton.edu/file-type/gis-data

Shapes selecionados:

1 - Basemap: Airport and Airbases
2 - Administrative Boundaries : 329 Districts
3 - Routes
4 - Basemap: Settlements

**Comment by ebl4** [comment]
A tabela de settlement precisa ser alterada para inserir o mesmo SRID das outras tabelas, se não ocorre erro de compatibilidade nas funções espaciais.

**geom geometry(Point, 4326),**

![image](https://cloud.githubusercontent.com/assets/6393137/11486106/abbe0cde-9795-11e5-9214-a9652511a51b.png)
